name: ultimate_alarm_clock
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  # objectbox_flutter_libs: ^1.7.2
  firebase_core: ^2.8.0
  screen_state: ^2.0.0
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_foreground_task: ^4.1.0
  flutter_ringtone_player: ^3.2.0
  flutter_time_picker_spinner: ^2.0.0
  cloud_firestore: ^4.4.5
  intl: ^0.18.0
  latlong2: ^0.8.1
  flutter_map: ^3.1.0
  app_minimizer: ^1.0.0+2
  fl_location: ^1.2.2
  flutter_fgbg: ^0.2.2
  flutter_svg: ^2.0.4
  isar: ^3.1.0+1
  async: ^2.10.0
  flutter:
    sdk: flutter
  isar_flutter_libs: ^3.1.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/raleway/Raleway-SemiBold.ttf
          weight: 600
  uses-material-design: true
  assets:
    - assets/images/
