name: ultimate_alarm_clock
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  screen_state: ^2.0.0
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_foreground_task: ^4.1.0
  flutter_ringtone_player: ^3.2.0
  flutter_time_picker_spinner: ^2.0.0
  sqflite: ^2.2.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/music/alarm.mp3
